# Generated by Django 5.0 on 2024-01-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_project_accomplish_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContigencyRate',
        ),
    ]
