# Generated by Django 5.0 on 2024-01-25 04:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_usercommitte_members_usercommitte_member1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost_estimate',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
        migrations.AlterField(
            model_name='usercommitte',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.project'),
        ),
    ]
