# Generated by Django 5.0 on 2024-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_cost_estimate_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='chairperson',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
